=== jvalue/open-data-service-v1/server/src/main/resources/nds/Weather.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:a="http://langdale.com.au/2005/Message#"
		   xmlns:sawsdl="http://www.w3.org/ns/sawsdl" targetNamespace="http://iec.ch/TC57/Weather#"
		   elementFormDefault="qualified" attributeFormDefault="unqualified"
		   xmlns="http://langdale.com.au/2005/Message#" xmlns:m="http://iec.ch/TC57/Weather#">
	<xs:annotation>
		<xs:documentation/>
	</xs:annotation>
	<xs:element name="Weather" type="m:Weather"/>
	<xs:complexType name="Weather">
		<xs:sequence>
			<xs:element name="EnvironmentalMonitoringStation" type="m:EnvironmentalMonitoringStation" minOccurs="1"
						maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AnalogValue" sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#AnalogValue">
		<xs:annotation>
			<xs:documentation>AnalogValue represents an analog MeasurementValue.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="timeStamp" minOccurs="1" maxOccurs="1" type="xs:dateTime"
						sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#MeasurementValue.timeStamp">
				<xs:annotation>
					<xs:documentation>The time when the value was last updated</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="value" minOccurs="1" maxOccurs="1" type="xs:float"
						sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#AnalogValue.value">
				<xs:annotation>
					<xs:documentation>The value to supervise.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AtmosphericAnalog" sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#AtmosphericAnalog">
		<xs:annotation>
			<xs:documentation>Analog (float) measuring an atmospheric condition.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="kind" minOccurs="1" maxOccurs="1" type="m:AtmosphericAnalogKind"
						sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#AtmosphericAnalog.kind">
				<xs:annotation>
					<xs:documentation>Kind of atmospheric analog.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="unitMultiplier" minOccurs="1" maxOccurs="1" type="m:UnitMultiplier"
						sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#Measurement.unitMultiplier">
				<xs:annotation>
					<xs:documentation>The unit multiplier of the measured quantity.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="unitSymbol" minOccurs="1" maxOccurs="1" type="m:UnitSymbol"
						sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#Measurement.unitSymbol">
				<xs:annotation>
					<xs:documentation>The unit of measure of the measured quantity.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="AnalogValues" minOccurs="1" maxOccurs="unbounded" type="m:AnalogValue"
						sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#Analog.AnalogValues">
				<xs:annotation>
					<xs:documentation>The values connected to this measurement.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="AtmosphericAnalogKind"
				   sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#AtmosphericAnalogKind">
		<xs:annotation>
			<xs:documentation>Kinds of analogs (floats) measuring an atmospheric condition.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="ambientTemperature">
				<xs:annotation>
					<xs:documentation>The temperature measured b&lt;font color="#0f0f0f"&gt;y a thermometer exposed to
						the air in a place sheltered from direct solar radiation. &lt;/font&gt;Also known as "dry bulb"
						because&lt;font color="#0f0f0f"&gt; the air temperature is indicated by a thermometer not
						affecte&lt;/font&gt;d by the moisture of the air.
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="irradianceGlobalHorizontal">
				<xs:annotation/>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="EnvironmentalMonitoringStation"
					sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#EnvironmentalMonitoringStation">
		<xs:annotation>
			<xs:documentation>An environmental monitoring station, examples of which could be a weather station or a
				seismic monitoring station.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="mRID" minOccurs="1" maxOccurs="1" type="xs:string"
						sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#IdentifiedObject.mRID">
				<xs:annotation>
					<xs:documentation>Master resource identifier issued by a model authority. The mRID is unique within
						an exchange context. Global uniqueness is easily achieved by using a UUID, as specified in RFC
						4122, for the mRID. The use of UUID is strongly recommended.
					</xs:documentation>
					<xs:documentation>For CIMXML data files in RDF syntax conforming to IEC 61970-552 Edition 1, the
						mRID is mapped to rdf:ID or rdf:about attributes that identify CIM object elements.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="EnvironmentalAnalog" minOccurs="1" maxOccurs="unbounded" type="m:AtmosphericAnalog"
						sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#EnvironmentalMonitoringStation.EnvironmentalAnalog">
				<xs:annotation>
					<xs:documentation>Environmental analog measurement provided by this monitoring station.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Location" minOccurs="1" maxOccurs="1" type="m:Location"
						sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#EnvironmentalMonitoringStation.Location">
				<xs:annotation>
					<xs:documentation>Location of this monitoring station.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Location" sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#Location">
		<xs:annotation>
			<xs:documentation>The place, scene, or point of something where someone or something has been, is, and/or
				will be at a given moment in time. It can be defined with one or more postition points (coordinates) in
				a given coordinate system.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="mainAddress" minOccurs="1" maxOccurs="1" type="m:StreetAddress"
						sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#Location.mainAddress">
				<xs:annotation>
					<xs:documentation>Main address of the location.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StreetAddress" sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#StreetAddress">
		<xs:annotation>
			<xs:documentation>General purpose street and postal address information.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="townDetail" minOccurs="1" maxOccurs="1" type="m:TownDetail"
						sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#StreetAddress.townDetail">
				<xs:annotation>
					<xs:documentation>Town detail.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TownDetail" sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#TownDetail">
		<xs:annotation>
			<xs:documentation>Town details, in the context of address.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="name" minOccurs="1" maxOccurs="1" type="xs:string"
						sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#TownDetail.name">
				<xs:annotation>
					<xs:documentation>Town name.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="UnitMultiplier" sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#UnitMultiplier">
		<xs:annotation>
			<xs:documentation>The unit multipliers defined for the CIM. When applied to unit symbols, the unit symbol is
				treated as a derived unit. Regardless of the contents of the unit symbol text, the unit symbol shall be
				treated as if it were a single-character unit symbol. Unit symbols should not contain multipliers, and
				it should be left to the multiplier to define the multiple for an entire data type.
			</xs:documentation>
			<xs:documentation>For example, if a unit symbol is "A2Perh" and the multiplier is "k", then the value is
				k(A^2/h), and the multiplier applies to the entire final value, not to any individual part of the value.
				This can be conceptualized by substituting a derived unit symbol for the unit type. If one imagines that
				the symbol "횧" represents the derived unit "A2Perh", then applying the multiplier "k" can be
				conceptualized simply as "k횧".
			</xs:documentation>
			<xs:documentation>For example, the SI unit for mass is "kg" and not "g". If the unit symbol is defined as
				"kg", then the multiplier is applied to "kg" as a whole and does not replace the "k" in front of the
				"g". In this case, the multiplier of "m" would be used with the unit symbol of "kg" to represent one
				gram. As a text string, this violates the instructions in IEC 80000-1. However, because the unit symbol
				in CIM is treated as a derived unit instead of as an SI unit, it makes more sense to conceptualize the
				"kg" as if it were replaced by one of the proposed replacements for the SI mass symbol. If one imagines
				that the "kg" were replaced by a symbol "횧", then it is easier to conceptualize the multiplier "m" as
				creating the proper unit "m횧", and not the forbidden unit "mkg".
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="E">
				<xs:annotation>
					<xs:documentation>Exa 10**18.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="G">
				<xs:annotation>
					<xs:documentation>Giga 10**9.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="M">
				<xs:annotation>
					<xs:documentation>Mega 10**6.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="P">
				<xs:annotation>
					<xs:documentation>Peta 10**15</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="T">
				<xs:annotation>
					<xs:documentation>Tera 10**12.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Y">
				<xs:annotation>
					<xs:documentation>Yotta 10**24</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Z">
				<xs:annotation>
					<xs:documentation>Zetta 10**21</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="a">
				<xs:annotation>
					<xs:documentation>atto 10**-18.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="c">
				<xs:annotation>
					<xs:documentation>Centi 10**-2.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="d">
				<xs:annotation>
					<xs:documentation>Deci 10**-1.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="da">
				<xs:annotation>
					<xs:documentation>deca 10**1.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="f">
				<xs:annotation>
					<xs:documentation>femto 10**-15.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="h">
				<xs:annotation>
					<xs:documentation>hecto 10**2.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="k">
				<xs:annotation>
					<xs:documentation>Kilo 10**3.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="m">
				<xs:annotation>
					<xs:documentation>Milli 10**-3.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="micro">
				<xs:annotation>
					<xs:documentation>Micro 10**-6.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="n">
				<xs:annotation>
					<xs:documentation>Nano 10**-9.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="none">
				<xs:annotation>
					<xs:documentation>No multiplier or equivalently multiply by 1.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="p">
				<xs:annotation>
					<xs:documentation>Pico 10**-12.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="y">
				<xs:annotation>
					<xs:documentation>yocto 10**-24.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="z">
				<xs:annotation>
					<xs:documentation>zepto 10**-21.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="UnitSymbol" sawsdl:modelReference="http://iec.ch/TC57/CIM-generic#UnitSymbol">
		<xs:annotation>
			<xs:documentation>The derived units defined for usage in the CIM. In some cases, the derived unit is equal
				to an SI unit. Whenever possible, the standard derived symbol is used instead of the formula for the
				derived unit. For example, the unit symbol Farad is defined as "F" instead of "CPerV". In cases where a
				standard symbol does not exist for a derived unit, the formula for the unit is used as the unit symbol.
				For example, density does not have a standard symbol and so it is represented as "kgPerm3". With the
				exception of the "kg", which is an SI unit, the unit symbols do not contain multipliers and therefore
				represent the base derived unit to which a multiplier can be applied as a whole.
			</xs:documentation>
			<xs:documentation>Every unit symbol is treated as an unparseable text as if it were a single-letter symbol.
				The meaning of each unit symbol is defined by the accompanying descriptive text and not by the text
				contents of the unit symbol.
			</xs:documentation>
			<xs:documentation>To allow the widest possible range of serializations without requiring special character
				handling, several substitutions are made which deviate from the format described in IEC 80000-1. The
				division symbol "/" is replaced by the letters"Per". Exponents are written in plain text after the unit
				as "m3" instead of being formatted as in "m&lt;sup&gt;3&lt;/sup&gt;" or introducing a symbol as in
				"m^3". The degree symbol "째" is replaced with the letters "deg". Any clarification of the meaning for a
				substitution is included in the description for the unit symbol.
			</xs:documentation>
			<xs:documentation>Non-SI units are included in list of unit symbols to allow sources of data to be correctly
				labeled with their non-SI units (for example, a GPS sensor that is reporting numbers that represent feet
				instead of meters). This allows software to use the unit symbol information correctly convert and scale
				the raw data of those sources into SI-based units.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="WPerm2">
				<xs:annotation>
					<xs:documentation>Heat flux density, irradiance, Watt per square metre.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="degC">
				<xs:annotation>
					<xs:documentation>Relative temperature in degrees Celsius.</xs:documentation>
					<xs:documentation>In the SI unit system the symbol is 쨘C. Electric charge is measured in coulomb
						that has the unit symbol C. To distinguish degree Celsius form coulomb the symbol used in the
						UML is degC. Reason for not using 쨘C is the special character 쨘 is difficult to manage in
						software.
					</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== jvalue/open-data-service-v1/server/src/main/resources/nds/CIM-Template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2019 Friedrich-Alexander University Erlangen-Nuernberg (FAU)

    SPDX-License-Identifier: AGPL-3.0-only

-->
<cim:Weather xmlns:cim="http://iec.ch/TC57/Weather#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://iec.ch/TC57/Weather# Weather.xsd">
	<cim:EnvironmentalMonitoringStation>
		<cim:mRID>String</cim:mRID>
		<cim:EnvironmentalAnalog>
			<cim:kind>ambientTemperature</cim:kind>
			<cim:unitMultiplier>none</cim:unitMultiplier>
			<cim:unitSymbol>degC</cim:unitSymbol>
			<cim:AnalogValues>
				<cim:timeStamp>__TIMESTAMP__</cim:timeStamp>
				<cim:value>__TEMP_IN_C__</cim:value>
			</cim:AnalogValues>
		</cim:EnvironmentalAnalog>
		<cim:EnvironmentalAnalog>
			<cim:kind>irradianceGlobalHorizontal</cim:kind>
			<cim:unitMultiplier>a</cim:unitMultiplier>
			<cim:unitSymbol>WPerm2</cim:unitSymbol>
			<cim:AnalogValues>
				<cim:timeStamp>__TIMESTAMP__</cim:timeStamp>
				<cim:value>__SOLAR_RADIATION__</cim:value>
			</cim:AnalogValues>
		</cim:EnvironmentalAnalog>
		<cim:Location>
			<cim:mainAddress>
				<cim:townDetail>
					<cim:name>__CITY__</cim:name>
				</cim:townDetail>
			</cim:mainAddress>
		</cim:Location>
	</cim:EnvironmentalMonitoringStation>
</cim:Weather>
